with source as 
(

    SELECT *
    FROM {{ source('public', 'raw_sales') }} 

),

renamed as

  (select
coalesce(sale_id::text, 'unknown') as id_vente,
coalesce(customer_id::text, 'unknown') as id_acheteur,
coalesce(store_id::text, 'unknown') as id_boutique_vente,
coalesce(replace(amount, ',', '')::numeric, 0) as montant_vente,
coalesce(utm_data__utm_source, 'unknown') as sourcevente,

CASE "origin_country__alpha3code"
    WHEN 'MDG' THEN 'Madagascar'
    WHEN 'TZA' THEN 'Tanzanie'
    WHEN 'NLD' THEN 'Pays-Bas'
    WHEN 'COG' THEN 'République du Congo'
    WHEN 'HUN' THEN 'Hongrie'
    WHEN 'AUT' THEN 'Autriche'
    WHEN 'MAF' THEN 'Saint-Martin'
    WHEN 'IRL' THEN 'Irlande'
    WHEN 'ISR' THEN 'Israël'
    WHEN 'GBR' THEN 'Royaume-Uni'
    WHEN 'CAF' THEN 'République centrafricaine'
    WHEN 'GMB' THEN 'Gambie'
    WHEN 'HKG' THEN 'Hong Kong'
    WHEN 'CPV' THEN 'Cap-Vert'
    WHEN 'BEL' THEN 'Belgique'
    WHEN 'MRT' THEN 'Mauritanie'
    WHEN 'VNM' THEN 'Vietnam'
    WHEN 'CZE' THEN 'République tchèque'
    WHEN 'VGB' THEN 'Îles Vierges britanniques'
    WHEN 'LBN' THEN 'Liban'
    WHEN 'LTU' THEN 'Lituanie'
    WHEN 'SVN' THEN 'Slovénie'
    WHEN 'CIV' THEN 'Côte d’Ivoire'
    WHEN 'PHL' THEN 'Philippines'
    WHEN 'DJI' THEN 'Djibouti'
    WHEN 'SEN' THEN 'Sénégal'
    WHEN 'ESP' THEN 'Espagne'
    WHEN 'TUN' THEN 'Tunisie'
    WHEN 'GHA' THEN 'Ghana'
    WHEN 'SGP' THEN 'Singapour'
    WHEN 'BRB' THEN 'Barbade'
    WHEN 'ROU' THEN 'Roumanie'
    WHEN 'GRC' THEN 'Grèce'
    WHEN 'LBR' THEN 'Liberia'
    WHEN 'GUF' THEN 'Guyane française'
    WHEN 'MYS' THEN 'Malaisie'
    WHEN 'GNB' THEN 'Guinée-Bissau'
    WHEN 'MYT' THEN 'Mayotte'
    WHEN 'VIR' THEN 'Îles Vierges américaines'
    WHEN 'HTI' THEN 'Haïti'
    WHEN 'NGA' THEN 'Nigeria'
    WHEN 'DOM' THEN 'République dominicaine'
    WHEN 'LIE' THEN 'Liechtenstein'
    WHEN 'LBY' THEN 'Libye'
    WHEN 'MUS' THEN 'Maurice'
    WHEN 'PRT' THEN 'Portugal'
    WHEN 'ZWE' THEN 'Zimbabwe'
    WHEN 'MTQ' THEN 'Martinique'
    WHEN 'NOR' THEN 'Norvège'
    WHEN 'ZMB' THEN 'Zambie'
    WHEN 'DNK' THEN 'Danemark'
    WHEN 'MDA' THEN 'Moldavie'
    WHEN 'AND' THEN 'Andorre'
    WHEN 'AGO' THEN 'Angola'
    WHEN 'GLP' THEN 'Guadeloupe'
    WHEN 'MWI' THEN 'Malawi'
    WHEN 'KHM' THEN 'Cambodge'
    WHEN 'IND' THEN 'Inde'
    WHEN 'EGY' THEN 'Égypte'
    WHEN 'CMR' THEN 'Cameroun'
    WHEN 'CHL' THEN 'Chili'
    WHEN 'GEO' THEN 'Géorgie'
    WHEN 'GTM' THEN 'Guatemala'
    WHEN 'USA' THEN 'États-Unis'
    WHEN 'LUX' THEN 'Luxembourg'
    WHEN 'NAM' THEN 'Namibie'
    WHEN 'BGD' THEN 'Bangladesh'
    WHEN 'COD' THEN 'République démocratique du Congo'
    WHEN 'FIN' THEN 'Finlande'
    WHEN 'SYC' THEN 'Seychelles'
    WHEN 'PAK' THEN 'Pakistan'
    WHEN 'BFA' THEN 'Burkina Faso'
    WHEN 'PAN' THEN 'Panama'
    WHEN 'DZA' THEN 'Algérie'
    WHEN 'UKR' THEN 'Ukraine'
    WHEN 'THA' THEN 'Thaïlande'
    WHEN 'BDI' THEN 'Burundi'
    WHEN 'KWT' THEN 'Koweït'
    WHEN 'GIN' THEN 'Guinée'
    WHEN 'MLI' THEN 'Mali'
    WHEN 'POL' THEN 'Pologne'
    WHEN 'TUR' THEN 'Turquie'
    WHEN 'SWE' THEN 'Suède'
    WHEN 'DEU' THEN 'Allemagne'
    WHEN 'IDN' THEN 'Indonésie'
    WHEN 'CYP' THEN 'Chypre'
    WHEN 'MOZ' THEN 'Mozambique'
    WHEN 'ARE' THEN 'Émirats arabes unis'
    WHEN 'SLE' THEN 'Sierra Leone'
    WHEN 'AUS' THEN 'Australie'
    WHEN 'PYF' THEN 'Polynésie française'
    WHEN 'GAB' THEN 'Gabon'
    WHEN 'FRA' THEN 'France'
    WHEN 'CHN' THEN 'Chine'
    WHEN 'UGA' THEN 'Ouganda'
    WHEN 'MAR' THEN 'Maroc'
    WHEN 'ZAF' THEN 'Afrique du Sud'
    WHEN 'CAN' THEN 'Canada'
    WHEN 'BWA' THEN 'Botswana'
    WHEN 'BRA' THEN 'Brésil'
    WHEN 'AFG' THEN 'Afghanistan'
    WHEN 'GNQ' THEN 'Guinée équatoriale'
    WHEN 'RWA' THEN 'Rwanda'
    WHEN 'CHE' THEN 'Suisse'
    WHEN 'KOR' THEN 'Corée du Sud'
    WHEN 'MCO' THEN 'Monaco'
    WHEN 'NCL' THEN 'Nouvelle-Calédonie'
    WHEN 'REU' THEN 'La Réunion'
    WHEN 'TGO' THEN 'Togo'
    WHEN 'YEM' THEN 'Yémen'
    WHEN 'ITA' THEN 'Italie'
    WHEN 'BEN' THEN 'Bénin'
    WHEN 'SAU' THEN 'Arabie saoudite'
    WHEN 'KEN' THEN 'Kenya'
    WHEN 'JPN' THEN 'Japon'
    WHEN 'NER' THEN 'Niger'
    WHEN 'COM' THEN 'Comores'
    WHEN 'MEX' THEN 'Mexique'
    WHEN 'TCD' THEN 'Tchad'
    WHEN 'ETH' THEN 'Éthiopie'
    ELSE 'Autre'
END AS pays_vente

from source 
)

select * from renamed